version: '3.8'

services:
  ben:
    build:
      context: .
    container_name: ben
    working_dir: /app
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '64'
    #     reservations:
    #       cpus: '32'
    ports:
      - "25000:25000"
    environment:
      - PORT=25000
      - DEVICE=cuda:7
    runtime: nvidia
    volumes:
      - ./src:/app
      - ./resources/selected_lora:/loras
      - ./resources/PubMedBERT:/models/microsoft/PubMedBERT
